apiVersion: v1
kind: Pod
metadata:
  name: webrtc
  labels:
    app: webrtc
spec:
  containers:
  - name: webrtc
    image: amirhossein21/webrtc:v0.2.0
    ports:
    - containerPort: 80
    env:
    - name: HTTP_PORT
      value: "80"
    - name: DEV_MODE
      value: "false"
    - name: APP_VERSION
      value: "v0.2.0-beta"

